### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by jmsunseri** [JaimeStill/aspnet-core-angular-material-integration#1]
I think this project needs a few updates.  everything has changed from md-* to mat-*

Would also be nice to do similar with a current template from VS 2017 .net core angular template.

**Comment by JaimeStill** [comment]
@jmsunseri , this is an older repository that I keep around for basic principles. See the following repos for a VS 2017 starter template and the project it's based on:  

[webstack-template](https://github.com/JaimeStill/webstack-template)  
[webstack](https://github.com/JaimeStill/webstack-template)

**Comment by jmsunseri** [comment]
sweet thanks!


Sincerely

Justin Sunseri
Please don't print this e-mail unless you really need to.
